import type {
  Account,
  AssetSnapshot,
  Category,
  Entity,
  InvestmentSnapshot,
  LiabilitySnapshot,
  ProviderConnection,
  Transaction,
} from "@/domain/types";

export const entities: Entity[] = [
  { id: "entity-private", name: "Private", type: "PRIVATE" },
  { id: "entity-holding", name: "Holding B.V.", type: "HOLDING_BV" },
  { id: "entity-operating", name: "Operating B.V.", type: "OPERATING_BV" },
  { id: "entity-uk", name: "UK LTD", type: "UK_LTD" },
];

export const categories: Category[] = [
  { id: "cat-uncategorised", name: "Uncategorised", color: "#68736b", isSystem: true },
  { id: "cat-wonen", name: "Wonen", color: "#236b4a" },
  { id: "cat-boodschappen", name: "Boodschappen", color: "#2563eb" },
  { id: "cat-horeca", name: "Eten & Horeca", color: "#b7791f" },
  { id: "cat-vervoer", name: "Vervoer", color: "#475569" },
  { id: "cat-zorg", name: "Zorg", color: "#0f766e" },
  { id: "cat-abonnementen", name: "Abonnementen", color: "#7c3aed" },
  { id: "cat-prive-overig", name: "Prive Overig", color: "#64748b" },
  { id: "cat-zakelijk-voorgeschoten", name: "Zakelijk Prive Voorgeschoten", color: "#0891b2" },
  { id: "cat-investering", name: "Investering", color: "#166534" },
  { id: "cat-crypto", name: "Crypto", color: "#0369a1" },
  { id: "cat-beleggen", name: "Beleggen", color: "#155e75" },
  { id: "cat-vastgoed", name: "Vastgoed", color: "#854d0e" },
  { id: "cat-belastingen", name: "Belastingen", color: "#991b1b" },
  { id: "cat-interne-transfer", name: "Interne Transfer", color: "#334155" },
  { id: "cat-inkomsten", name: "Inkomsten", color: "#15803d" },
  { id: "cat-salaris-draw", name: "Salaris / Draw", color: "#047857" },
  { id: "cat-holding-private-flow", name: "Holding / Private Flow", color: "#0f766e" },
];

export const accounts: Account[] = [
  {
    id: "acc-private-abn",
    name: "ABN AMRO Private",
    entityId: "entity-private",
    source: "ABN_AMRO",
    class: "BANK",
    liquidity: "LIQUID",
    balance: 48750,
    lastUpdated: "2026-04-29T07:32:00.000Z",
    syncStatus: "HEALTHY",
    includeInConsolidated: true,
  },
  {
    id: "acc-holding-abn",
    name: "ABN AMRO Holding",
    entityId: "entity-holding",
    source: "ABN_AMRO",
    class: "BANK",
    liquidity: "LIQUID",
    balance: 186400,
    lastUpdated: "2026-04-29T07:31:00.000Z",
    syncStatus: "HEALTHY",
    includeInConsolidated: true,
  },
  {
    id: "acc-revolut-uk",
    name: "Revolut Business UK LTD",
    entityId: "entity-uk",
    source: "REVOLUT",
    class: "BANK",
    liquidity: "LIQUID",
    balance: 34850,
    lastUpdated: "2026-04-29T06:51:00.000Z",
    syncStatus: "STALE",
    includeInConsolidated: true,
  },
  {
    id: "acc-bitvavo",
    name: "Bitvavo Crypto",
    entityId: "entity-private",
    source: "BITVAVO",
    class: "CRYPTO",
    liquidity: "LIQUID",
    balance: 82300,
    lastUpdated: "2026-04-29T07:40:00.000Z",
    syncStatus: "HEALTHY",
    includeInConsolidated: true,
  },
  {
    id: "acc-degiro",
    name: "DEGIRO Investments",
    entityId: "entity-private",
    source: "DEGIRO",
    class: "BROKER",
    liquidity: "LIQUID",
    balance: 214900,
    lastUpdated: "2026-04-28T18:20:00.000Z",
    syncStatus: "HEALTHY",
    includeInConsolidated: true,
  },
  {
    id: "acc-property-home",
    name: "Amsterdam House",
    entityId: "entity-private",
    source: "MANUAL",
    class: "PROPERTY",
    liquidity: "ILLIQUID",
    balance: 925000,
    lastUpdated: "2026-04-01T00:00:00.000Z",
    syncStatus: "MANUAL",
    includeInConsolidated: true,
  },
  {
    id: "acc-mortgage",
    name: "Mortgage House",
    entityId: "entity-private",
    source: "MANUAL",
    class: "LIABILITY",
    liquidity: "ILLIQUID",
    balance: -548000,
    lastUpdated: "2026-04-01T00:00:00.000Z",
    syncStatus: "MANUAL",
    includeInConsolidated: true,
  },
  {
    id: "acc-holding-private-loan",
    name: "Holding Loan to Private",
    entityId: "entity-private",
    source: "MANUAL",
    class: "LIABILITY",
    liquidity: "ILLIQUID",
    balance: -76000,
    lastUpdated: "2026-04-01T00:00:00.000Z",
    syncStatus: "MANUAL",
    includeInConsolidated: true,
  },
];

export const transactions: Transaction[] = [
  {
    id: "txn-001",
    date: "2026-04-26",
    description: "Founder salary draw",
    accountId: "acc-private-abn",
    entityId: "entity-private",
    categoryId: "cat-salaris-draw",
    amount: 7800,
    direction: "INFLOW",
    isInternalTransfer: true,
    isInvestmentRelated: false,
    liquidityImpact: "LIQUID",
    counterparty: "Holding B.V.",
    tags: ["draw", "internal-flow"],
  },
  {
    id: "txn-002",
    date: "2026-04-26",
    description: "Transfer to private",
    accountId: "acc-holding-abn",
    entityId: "entity-holding",
    categoryId: "cat-holding-private-flow",
    amount: -7800,
    direction: "OUTFLOW",
    isInternalTransfer: true,
    isInvestmentRelated: false,
    liquidityImpact: "LIQUID",
    counterparty: "Private ABN",
    tags: ["internal-flow"],
  },
  {
    id: "txn-003",
    date: "2026-04-24",
    description: "UK client retainer",
    accountId: "acc-revolut-uk",
    entityId: "entity-uk",
    categoryId: "cat-inkomsten",
    amount: 18500,
    direction: "INFLOW",
    isInternalTransfer: false,
    isInvestmentRelated: false,
    liquidityImpact: "LIQUID",
    counterparty: "Northstar Labs Ltd",
    tags: ["revenue"],
  },
  {
    id: "txn-004",
    date: "2026-04-22",
    description: "Operating dividend to holding",
    accountId: "acc-holding-abn",
    entityId: "entity-holding",
    categoryId: "cat-holding-private-flow",
    amount: 42000,
    direction: "INFLOW",
    isInternalTransfer: true,
    isInvestmentRelated: false,
    liquidityImpact: "LIQUID",
    counterparty: "Operating B.V.",
    tags: ["internal-flow", "operating-to-holding"],
  },
  {
    id: "txn-005",
    date: "2026-04-21",
    description: "Mortgage payment",
    accountId: "acc-private-abn",
    entityId: "entity-private",
    categoryId: "cat-wonen",
    amount: -2950,
    direction: "OUTFLOW",
    isInternalTransfer: false,
    isInvestmentRelated: false,
    liquidityImpact: "MIXED",
    counterparty: "ABN AMRO Hypotheken",
    tags: ["recurring"],
  },
  {
    id: "txn-006",
    date: "2026-04-18",
    description: "Albert Heijn",
    accountId: "acc-private-abn",
    entityId: "entity-private",
    categoryId: "cat-boodschappen",
    amount: -186.42,
    direction: "OUTFLOW",
    isInternalTransfer: false,
    isInvestmentRelated: false,
    liquidityImpact: "LIQUID",
    tags: ["household"],
  },
  {
    id: "txn-007",
    date: "2026-04-15",
    description: "DEGIRO cash deposit",
    accountId: "acc-private-abn",
    entityId: "entity-private",
    categoryId: "cat-beleggen",
    amount: -15000,
    direction: "OUTFLOW",
    isInternalTransfer: true,
    isInvestmentRelated: true,
    liquidityImpact: "LIQUID",
    counterparty: "DEGIRO",
    tags: ["investment-transfer"],
  },
  {
    id: "txn-008",
    date: "2026-04-15",
    description: "Deposit received",
    accountId: "acc-degiro",
    entityId: "entity-private",
    categoryId: "cat-beleggen",
    amount: 15000,
    direction: "INFLOW",
    isInternalTransfer: true,
    isInvestmentRelated: true,
    liquidityImpact: "LIQUID",
    counterparty: "ABN AMRO Private",
    tags: ["investment-transfer"],
  },
  {
    id: "txn-009",
    date: "2026-04-12",
    description: "Stripe subscription",
    accountId: "acc-revolut-uk",
    entityId: "entity-uk",
    categoryId: "cat-abonnementen",
    amount: -274,
    direction: "OUTFLOW",
    isInternalTransfer: false,
    isInvestmentRelated: false,
    liquidityImpact: "LIQUID",
    tags: ["saas", "recurring"],
  },
  {
    id: "txn-010",
    date: "2026-04-10",
    description: "Bitvavo EUR deposit",
    accountId: "acc-private-abn",
    entityId: "entity-private",
    categoryId: "cat-crypto",
    amount: -5000,
    direction: "OUTFLOW",
    isInternalTransfer: true,
    isInvestmentRelated: true,
    liquidityImpact: "LIQUID",
    counterparty: "Bitvavo",
    tags: ["crypto-transfer"],
  },
  {
    id: "txn-011",
    date: "2026-04-07",
    description: "Restaurant Amsterdam",
    accountId: "acc-private-abn",
    entityId: "entity-private",
    categoryId: "cat-horeca",
    amount: -244.8,
    direction: "OUTFLOW",
    isInternalTransfer: false,
    isInvestmentRelated: false,
    liquidityImpact: "LIQUID",
    tags: ["personal"],
  },
  {
    id: "txn-012",
    date: "2026-04-04",
    description: "Unmapped card payment",
    accountId: "acc-private-abn",
    entityId: "entity-private",
    categoryId: "cat-uncategorised",
    amount: -612.95,
    direction: "OUTFLOW",
    isInternalTransfer: false,
    isInvestmentRelated: false,
    liquidityImpact: "LIQUID",
    notes: "Needs review",
    tags: [],
  },
  {
    id: "txn-013",
    date: "2026-03-27",
    description: "Founder salary draw",
    accountId: "acc-private-abn",
    entityId: "entity-private",
    categoryId: "cat-salaris-draw",
    amount: 7800,
    direction: "INFLOW",
    isInternalTransfer: true,
    isInvestmentRelated: false,
    liquidityImpact: "LIQUID",
    tags: ["draw", "internal-flow"],
  },
  {
    id: "txn-014",
    date: "2026-03-20",
    description: "Mortgage payment",
    accountId: "acc-private-abn",
    entityId: "entity-private",
    categoryId: "cat-wonen",
    amount: -2950,
    direction: "OUTFLOW",
    isInternalTransfer: false,
    isInvestmentRelated: false,
    liquidityImpact: "MIXED",
    tags: ["recurring"],
  },
  {
    id: "txn-015",
    date: "2026-03-11",
    description: "Bunq legacy payment",
    accountId: "acc-private-abn",
    entityId: "entity-private",
    categoryId: "cat-uncategorised",
    amount: -430,
    direction: "OUTFLOW",
    isInternalTransfer: false,
    isInvestmentRelated: false,
    liquidityImpact: "LIQUID",
    tags: [],
  },
];

const months = ["2025-11", "2025-12", "2026-01", "2026-02", "2026-03", "2026-04"];

export const assetSnapshots: AssetSnapshot[] = months.flatMap((month, index) => [
  {
    id: `asset-cash-${month}`,
    month,
    accountId: "acc-private-abn",
    entityId: "entity-private",
    assetClass: "BANK",
    liquidity: "LIQUID",
    value: 39000 + index * 1950,
  },
  {
    id: `asset-holding-${month}`,
    month,
    accountId: "acc-holding-abn",
    entityId: "entity-holding",
    assetClass: "BANK",
    liquidity: "LIQUID",
    value: 142000 + index * 8880,
  },
  {
    id: `asset-uk-${month}`,
    month,
    accountId: "acc-revolut-uk",
    entityId: "entity-uk",
    assetClass: "BANK",
    liquidity: "LIQUID",
    value: 25000 + index * 1970,
  },
  {
    id: `asset-bitvavo-${month}`,
    month,
    accountId: "acc-bitvavo",
    entityId: "entity-private",
    assetClass: "CRYPTO",
    liquidity: "LIQUID",
    value: 61000 + index * 4260,
  },
  {
    id: `asset-degiro-${month}`,
    month,
    accountId: "acc-degiro",
    entityId: "entity-private",
    assetClass: "BROKER",
    liquidity: "LIQUID",
    value: 181000 + index * 6780,
  },
  {
    id: `asset-property-${month}`,
    month,
    accountId: "acc-property-home",
    entityId: "entity-private",
    assetClass: "PROPERTY",
    liquidity: "ILLIQUID",
    value: 910000 + index * 3000,
  },
]);

export const liabilitySnapshots: LiabilitySnapshot[] = months.flatMap((month, index) => [
  {
    id: `liability-mortgage-${month}`,
    month,
    name: "Mortgage House",
    entityId: "entity-private",
    liquidity: "ILLIQUID",
    value: 555500 - index * 1500,
  },
  {
    id: `liability-holding-loan-${month}`,
    month,
    name: "Holding Loan to Private",
    entityId: "entity-private",
    liquidity: "ILLIQUID",
    value: 76000,
  },
]);

export const investmentSnapshots: InvestmentSnapshot[] = months.flatMap((month, index) => [
  {
    id: `investment-bitvavo-${month}`,
    month,
    accountId: "acc-bitvavo",
    provider: "BITVAVO",
    assetType: "CRYPTO",
    contributed: 58000 + index * 5000,
    currentValue: 61000 + index * 4260,
    realizedGainLoss: index > 3 ? 1200 : 0,
  },
  {
    id: `investment-degiro-${month}`,
    month,
    accountId: "acc-degiro",
    provider: "DEGIRO",
    assetType: "ETF",
    contributed: 170000 + index * 7000,
    currentValue: 181000 + index * 6780,
    realizedGainLoss: 850 + index * 120,
  },
]);

export const connections: ProviderConnection[] = [
  {
    id: "conn-abn",
    provider: "ABN_AMRO",
    displayName: "ABN AMRO",
    status: "CONNECTED",
    lastSync: "2026-04-29T07:32:00.000Z",
    syncHealth: "2 accounts synced",
  },
  {
    id: "conn-bitvavo",
    provider: "BITVAVO",
    displayName: "Bitvavo",
    status: "CONNECTED",
    lastSync: "2026-04-29T07:40:00.000Z",
    syncHealth: "Balances and positions synced",
  },
  {
    id: "conn-revolut",
    provider: "REVOLUT",
    displayName: "Revolut Business",
    status: "RECONNECT_REQUIRED",
    lastSync: "2026-04-29T06:51:00.000Z",
    syncHealth: "Token expires soon",
  },
  {
    id: "conn-degiro",
    provider: "DEGIRO",
    displayName: "DEGIRO",
    status: "CONNECTED",
    lastSync: "2026-04-28T18:20:00.000Z",
    syncHealth: "Fallback adapter ready for broker sync",
  },
];

export function getEntityName(entityId: string) {
  return entities.find((entity) => entity.id === entityId)?.name ?? "Unknown entity";
}

export function getAccountName(accountId: string) {
  return accounts.find((account) => account.id === accountId)?.name ?? "Unknown account";
}

export function getCategoryName(categoryId: string) {
  return categories.find((category) => category.id === categoryId)?.name ?? "Unknown category";
}
